// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVrS_MD3iRoe3I6OL3mqeTmwcoMIn4I8c',
    appId: '1:657344197924:web:0a35bd056af3d9b6362fb1',
    messagingSenderId: '657344197924',
    projectId: 'candid-cf9fc',
    authDomain: 'candid-cf9fc.firebaseapp.com',
    databaseURL: 'https://candid-cf9fc-default-rtdb.firebaseio.com',
    storageBucket: 'candid-cf9fc.appspot.com',
    measurementId: 'G-WTQC8F6Y12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI9U3lfRpFuWK66wRyh6_GKbBA-tcCJeE',
    appId: '1:657344197924:android:bed8ae47a813d1ee362fb1',
    messagingSenderId: '657344197924',
    projectId: 'candid-cf9fc',
    databaseURL: 'https://candid-cf9fc-default-rtdb.firebaseio.com',
    storageBucket: 'candid-cf9fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8RN9ywUrLtWq7MQwPjAkgdbj00mGcrNc',
    appId: '1:657344197924:ios:ca71dabbf6ea6612362fb1',
    messagingSenderId: '657344197924',
    projectId: 'candid-cf9fc',
    databaseURL: 'https://candid-cf9fc-default-rtdb.firebaseio.com',
    storageBucket: 'candid-cf9fc.appspot.com',
    androidClientId: '657344197924-0prqedtjndbtg707576r0qjh7702tge8.apps.googleusercontent.com',
    iosClientId: '657344197924-o60bar34m8q3ei8nmgelblsqph7vof2q.apps.googleusercontent.com',
    iosBundleId: 'com.seller01.candid',
  );

}